/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapProductsDotxmlRouteImport } from './routes/sitemap-products[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SitemapCategoriesDotxmlRouteImport } from './routes/sitemap-categories[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MyCollectionsRouteImport } from './routes/my-collections'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DebugEnvRouteImport } from './routes/debug-env'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionIdRouteImport } from './routes/collection_.$id'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPromptsRouteImport } from './routes/_authenticated/admin.prompts'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPipelineRouteImport } from './routes/_authenticated/admin.pipeline'
import { Route as AuthenticatedAdminHierarchyRouteImport } from './routes/_authenticated/admin.hierarchy'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin.diagnostics'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCollectionsRouteImport } from './routes/_authenticated/admin.collections'
import { Route as AuthenticatedAdminBusinessRouteImport } from './routes/_authenticated/admin.business'
import { Route as AuthenticatedAdminAiTemplatesRouteImport } from './routes/_authenticated/admin.ai-templates'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin.products.new'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin.products.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'
import { Route as AuthenticatedAdminCollectionsIdRouteImport } from './routes/_authenticated/admin.collections_.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProductsDotxmlRoute = SitemapProductsDotxmlRouteImport.update({
  id: '/sitemap-products.xml',
  path: '/sitemap-products.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCategoriesDotxmlRoute = SitemapCategoriesDotxmlRouteImport.update({
  id: '/sitemap-categories.xml',
  path: '/sitemap-categories.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCollectionsRoute = MyCollectionsRouteImport.update({
  id: '/my-collections',
  path: '/my-collections',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEnvRoute = DebugEnvRouteImport.update({
  id: '/debug-env',
  path: '/debug-env',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIdRoute = CollectionIdRouteImport.update({
  id: '/collection_/$id',
  path: '/collection/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPromptsRoute =
  AuthenticatedAdminPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPipelineRoute =
  AuthenticatedAdminPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHierarchyRoute =
  AuthenticatedAdminHierarchyRouteImport.update({
    id: '/hierarchy',
    path: '/hierarchy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCollectionsRoute =
  AuthenticatedAdminCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessRoute =
  AuthenticatedAdminBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiTemplatesRoute =
  AuthenticatedAdminAiTemplatesRouteImport.update({
    id: '/ai-templates',
    path: '/ai-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminCollectionsIdRoute =
  AuthenticatedAdminCollectionsIdRouteImport.update({
    id: '/collections_/$id',
    path: '/collections/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/debug-env': typeof DebugEnvRoute
  '/home': typeof HomeRoute
  '/my-collections': typeof MyCollectionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/ai-templates': typeof AuthenticatedAdminAiTemplatesRoute
  '/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/hierarchy': typeof AuthenticatedAdminHierarchyRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/collections/$id': typeof AuthenticatedAdminCollectionsIdRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/debug-env': typeof DebugEnvRoute
  '/home': typeof HomeRoute
  '/my-collections': typeof MyCollectionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collection/$id': typeof CollectionIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/ai-templates': typeof AuthenticatedAdminAiTemplatesRoute
  '/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/hierarchy': typeof AuthenticatedAdminHierarchyRoute
  '/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/collections/$id': typeof AuthenticatedAdminCollectionsIdRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/debug-env': typeof DebugEnvRoute
  '/home': typeof HomeRoute
  '/my-collections': typeof MyCollectionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap-categories.xml': typeof SitemapCategoriesDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-products.xml': typeof SitemapProductsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/collection_/$id': typeof CollectionIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/ai-templates': typeof AuthenticatedAdminAiTemplatesRoute
  '/_authenticated/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/_authenticated/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/hierarchy': typeof AuthenticatedAdminHierarchyRoute
  '/_authenticated/admin/pipeline': typeof AuthenticatedAdminPipelineRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/prompts': typeof AuthenticatedAdminPromptsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/collections_/$id': typeof AuthenticatedAdminCollectionsIdRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/auth'
    | '/collection'
    | '/contact'
    | '/debug-env'
    | '/home'
    | '/my-collections'
    | '/robots.txt'
    | '/search'
    | '/sitemap-categories.xml'
    | '/sitemap-images.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/admin'
    | '/favorites'
    | '/settings'
    | '/collection/$id'
    | '/product/$slug'
    | '/admin/ai-templates'
    | '/admin/business'
    | '/admin/collections'
    | '/admin/customers'
    | '/admin/diagnostics'
    | '/admin/email'
    | '/admin/hierarchy'
    | '/admin/pipeline'
    | '/admin/products'
    | '/admin/prompts'
    | '/admin/'
    | '/admin/collections/$id'
    | '/admin/customers/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/auth'
    | '/collection'
    | '/contact'
    | '/debug-env'
    | '/home'
    | '/my-collections'
    | '/robots.txt'
    | '/search'
    | '/sitemap-categories.xml'
    | '/sitemap-images.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/favorites'
    | '/settings'
    | '/collection/$id'
    | '/product/$slug'
    | '/admin/ai-templates'
    | '/admin/business'
    | '/admin/collections'
    | '/admin/customers'
    | '/admin/diagnostics'
    | '/admin/email'
    | '/admin/hierarchy'
    | '/admin/pipeline'
    | '/admin/products'
    | '/admin/prompts'
    | '/admin'
    | '/admin/collections/$id'
    | '/admin/customers/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/account'
    | '/auth'
    | '/collection'
    | '/contact'
    | '/debug-env'
    | '/home'
    | '/my-collections'
    | '/robots.txt'
    | '/search'
    | '/sitemap-categories.xml'
    | '/sitemap-images.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-products.xml'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/settings'
    | '/collection_/$id'
    | '/product/$slug'
    | '/_authenticated/admin/ai-templates'
    | '/_authenticated/admin/business'
    | '/_authenticated/admin/collections'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/hierarchy'
    | '/_authenticated/admin/pipeline'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/prompts'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/collections_/$id'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  DebugEnvRoute: typeof DebugEnvRoute
  HomeRoute: typeof HomeRoute
  MyCollectionsRoute: typeof MyCollectionsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapCategoriesDotxmlRoute: typeof SitemapCategoriesDotxmlRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapProductsDotxmlRoute: typeof SitemapProductsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CollectionIdRoute: typeof CollectionIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-products.xml': {
      id: '/sitemap-products.xml'
      path: '/sitemap-products.xml'
      fullPath: '/sitemap-products.xml'
      preLoaderRoute: typeof SitemapProductsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-categories.xml': {
      id: '/sitemap-categories.xml'
      path: '/sitemap-categories.xml'
      fullPath: '/sitemap-categories.xml'
      preLoaderRoute: typeof SitemapCategoriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-collections': {
      id: '/my-collections'
      path: '/my-collections'
      fullPath: '/my-collections'
      preLoaderRoute: typeof MyCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-env': {
      id: '/debug-env'
      path: '/debug-env'
      fullPath: '/debug-env'
      preLoaderRoute: typeof DebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection_/$id': {
      id: '/collection_/$id'
      path: '/collection/$id'
      fullPath: '/collection/$id'
      preLoaderRoute: typeof CollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prompts': {
      id: '/_authenticated/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AuthenticatedAdminPromptsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pipeline': {
      id: '/_authenticated/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AuthenticatedAdminPipelineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hierarchy': {
      id: '/_authenticated/admin/hierarchy'
      path: '/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AuthenticatedAdminHierarchyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/collections': {
      id: '/_authenticated/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/business': {
      id: '/_authenticated/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AuthenticatedAdminBusinessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-templates': {
      id: '/_authenticated/admin/ai-templates'
      path: '/ai-templates'
      fullPath: '/admin/ai-templates'
      preLoaderRoute: typeof AuthenticatedAdminAiTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/collections_/$id': {
      id: '/_authenticated/admin/collections_/$id'
      path: '/collections/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiTemplatesRoute: typeof AuthenticatedAdminAiTemplatesRoute
  AuthenticatedAdminBusinessRoute: typeof AuthenticatedAdminBusinessRoute
  AuthenticatedAdminCollectionsRoute: typeof AuthenticatedAdminCollectionsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminHierarchyRoute: typeof AuthenticatedAdminHierarchyRoute
  AuthenticatedAdminPipelineRoute: typeof AuthenticatedAdminPipelineRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminPromptsRoute: typeof AuthenticatedAdminPromptsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCollectionsIdRoute: typeof AuthenticatedAdminCollectionsIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiTemplatesRoute: AuthenticatedAdminAiTemplatesRoute,
  AuthenticatedAdminBusinessRoute: AuthenticatedAdminBusinessRoute,
  AuthenticatedAdminCollectionsRoute: AuthenticatedAdminCollectionsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminHierarchyRoute: AuthenticatedAdminHierarchyRoute,
  AuthenticatedAdminPipelineRoute: AuthenticatedAdminPipelineRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRouteWithChildren,
  AuthenticatedAdminPromptsRoute: AuthenticatedAdminPromptsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCollectionsIdRoute: AuthenticatedAdminCollectionsIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  DebugEnvRoute: DebugEnvRoute,
  HomeRoute: HomeRoute,
  MyCollectionsRoute: MyCollectionsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapCategoriesDotxmlRoute: SitemapCategoriesDotxmlRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapProductsDotxmlRoute: SitemapProductsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CollectionIdRoute: CollectionIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
